### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by timshutes** [NolanChan/ESVBibleWorkflow#1]
Hi - I know this is 4 years old, but I wonder how hard it would be to update to API v3 so this could continue to work? This is my favorite workflow as a pastor, I use this ALL the time. Especially helpful now that esvbible.org has inexplicably made copying text so much harder.

Anyway, I'm sure it's not too difficult, but the script throws and error now "the IP key is no longer supported"

**Comment by PatrickF1** [comment]
Hi Tim. Nice to meet you! Wow that's so cool that you use it! Nolan and I will see what we can do. It may be a while before we fix it but know that it is on our minds, especially since we (or at least I), was using this regularly before it broke.

**Comment by timshutes** [comment]
Thanks for the response. Do you think it would be a time consuming fix? I
think everyone might need to have their own API app in order to make it
work w/ the new authentication. I appreciated the simplicity of this
workflow. Others are a bit more convoluted (IMO). Thanks again - regardless
of whether or not you get around to fixing it, it was really great while it
lasted.

~ Tim

**Comment by fly4him17** [comment]
Patrick and Nolan,

I'm a heavy user of this workflow as well. I've tried to fix it, but lack the skills. A user named emmanuel has updated this to work with the new api but his workflow is very limited and does not include a search by key word.

http://www.packal.org/workflow/esv-online-bible

Count me as one eager for this fix as well.

**Comment by NolanChan** [comment]
Ahh, sorry about not updating this for the time being 😅 I should be able to look into this this weekend. Hopefully I'll be able to figure out what happened!

**Comment by timshutes** [comment]
That's awesome! Thank you


~ Tim

**Comment by fly4him17** [comment]
Hey guys, any progress on this? I still feel crippled without it.

Thanks for your help and consideration.

**Comment by PatrickF1** [comment]
Hey guys, sorry we never got around to fixing this. In case you guys didn't notice, there is another workflow that has been updated to work with v3 of ESV's API. Since v3 does not include word search, this other workflow does not support it but it does support reference search still. Enjoy!
https://github.com/emmanueljl/ESV-Bible-Alfred-workflow
